// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface BlockIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.BlockID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes hash = 1;</code>
   */
  com.google.protobuf.ByteString getHash();

  /**
   * <code>.com.ono.chain.jabci.types.PartSetHeader parts_header = 2;</code>
   */
  boolean hasPartsHeader();
  /**
   * <code>.com.ono.chain.jabci.types.PartSetHeader parts_header = 2;</code>
   */
  com.ono.chain.jabci.types.PartSetHeader getPartsHeader();
  /**
   * <code>.com.ono.chain.jabci.types.PartSetHeader parts_header = 2;</code>
   */
  com.ono.chain.jabci.types.PartSetHeaderOrBuilder getPartsHeaderOrBuilder();
}
