// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface ConsensusParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.ConsensusParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.ono.chain.jabci.types.BlockSizeParams block_size = 1;</code>
   */
  boolean hasBlockSize();
  /**
   * <code>.com.ono.chain.jabci.types.BlockSizeParams block_size = 1;</code>
   */
  com.ono.chain.jabci.types.BlockSizeParams getBlockSize();
  /**
   * <code>.com.ono.chain.jabci.types.BlockSizeParams block_size = 1;</code>
   */
  com.ono.chain.jabci.types.BlockSizeParamsOrBuilder getBlockSizeOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.EvidenceParams evidence = 2;</code>
   */
  boolean hasEvidence();
  /**
   * <code>.com.ono.chain.jabci.types.EvidenceParams evidence = 2;</code>
   */
  com.ono.chain.jabci.types.EvidenceParams getEvidence();
  /**
   * <code>.com.ono.chain.jabci.types.EvidenceParams evidence = 2;</code>
   */
  com.ono.chain.jabci.types.EvidenceParamsOrBuilder getEvidenceOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ValidatorParams validator = 3;</code>
   */
  boolean hasValidator();
  /**
   * <code>.com.ono.chain.jabci.types.ValidatorParams validator = 3;</code>
   */
  com.ono.chain.jabci.types.ValidatorParams getValidator();
  /**
   * <code>.com.ono.chain.jabci.types.ValidatorParams validator = 3;</code>
   */
  com.ono.chain.jabci.types.ValidatorParamsOrBuilder getValidatorOrBuilder();
}
