// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface KVPairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.KVPair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes key = 1;</code>
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>bytes value = 2;</code>
   */
  com.google.protobuf.ByteString getValue();
}
