// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface ProofOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.Proof)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ono.chain.jabci.types.ProofOp ops = 1;</code>
   */
  java.util.List<com.ono.chain.jabci.types.ProofOp> 
      getOpsList();
  /**
   * <code>repeated .com.ono.chain.jabci.types.ProofOp ops = 1;</code>
   */
  com.ono.chain.jabci.types.ProofOp getOps(int index);
  /**
   * <code>repeated .com.ono.chain.jabci.types.ProofOp ops = 1;</code>
   */
  int getOpsCount();
  /**
   * <code>repeated .com.ono.chain.jabci.types.ProofOp ops = 1;</code>
   */
  java.util.List<? extends com.ono.chain.jabci.types.ProofOpOrBuilder> 
      getOpsOrBuilderList();
  /**
   * <code>repeated .com.ono.chain.jabci.types.ProofOp ops = 1;</code>
   */
  com.ono.chain.jabci.types.ProofOpOrBuilder getOpsOrBuilder(
      int index);
}
