// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface RequestEndBlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.RequestEndBlock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 height = 1;</code>
   */
  long getHeight();
}
