// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.ono.chain.jabci.types.RequestEcho echo = 2;</code>
   */
  boolean hasEcho();
  /**
   * <code>.com.ono.chain.jabci.types.RequestEcho echo = 2;</code>
   */
  com.ono.chain.jabci.types.RequestEcho getEcho();
  /**
   * <code>.com.ono.chain.jabci.types.RequestEcho echo = 2;</code>
   */
  com.ono.chain.jabci.types.RequestEchoOrBuilder getEchoOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.RequestFlush flush = 3;</code>
   */
  boolean hasFlush();
  /**
   * <code>.com.ono.chain.jabci.types.RequestFlush flush = 3;</code>
   */
  com.ono.chain.jabci.types.RequestFlush getFlush();
  /**
   * <code>.com.ono.chain.jabci.types.RequestFlush flush = 3;</code>
   */
  com.ono.chain.jabci.types.RequestFlushOrBuilder getFlushOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.RequestInfo info = 4;</code>
   */
  boolean hasInfo();
  /**
   * <code>.com.ono.chain.jabci.types.RequestInfo info = 4;</code>
   */
  com.ono.chain.jabci.types.RequestInfo getInfo();
  /**
   * <code>.com.ono.chain.jabci.types.RequestInfo info = 4;</code>
   */
  com.ono.chain.jabci.types.RequestInfoOrBuilder getInfoOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.RequestSetOption set_option = 5;</code>
   */
  boolean hasSetOption();
  /**
   * <code>.com.ono.chain.jabci.types.RequestSetOption set_option = 5;</code>
   */
  com.ono.chain.jabci.types.RequestSetOption getSetOption();
  /**
   * <code>.com.ono.chain.jabci.types.RequestSetOption set_option = 5;</code>
   */
  com.ono.chain.jabci.types.RequestSetOptionOrBuilder getSetOptionOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.RequestInitChain init_chain = 6;</code>
   */
  boolean hasInitChain();
  /**
   * <code>.com.ono.chain.jabci.types.RequestInitChain init_chain = 6;</code>
   */
  com.ono.chain.jabci.types.RequestInitChain getInitChain();
  /**
   * <code>.com.ono.chain.jabci.types.RequestInitChain init_chain = 6;</code>
   */
  com.ono.chain.jabci.types.RequestInitChainOrBuilder getInitChainOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.RequestQuery query = 7;</code>
   */
  boolean hasQuery();
  /**
   * <code>.com.ono.chain.jabci.types.RequestQuery query = 7;</code>
   */
  com.ono.chain.jabci.types.RequestQuery getQuery();
  /**
   * <code>.com.ono.chain.jabci.types.RequestQuery query = 7;</code>
   */
  com.ono.chain.jabci.types.RequestQueryOrBuilder getQueryOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.RequestBeginBlock begin_block = 8;</code>
   */
  boolean hasBeginBlock();
  /**
   * <code>.com.ono.chain.jabci.types.RequestBeginBlock begin_block = 8;</code>
   */
  com.ono.chain.jabci.types.RequestBeginBlock getBeginBlock();
  /**
   * <code>.com.ono.chain.jabci.types.RequestBeginBlock begin_block = 8;</code>
   */
  com.ono.chain.jabci.types.RequestBeginBlockOrBuilder getBeginBlockOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.RequestCheckTx check_tx = 9;</code>
   */
  boolean hasCheckTx();
  /**
   * <code>.com.ono.chain.jabci.types.RequestCheckTx check_tx = 9;</code>
   */
  com.ono.chain.jabci.types.RequestCheckTx getCheckTx();
  /**
   * <code>.com.ono.chain.jabci.types.RequestCheckTx check_tx = 9;</code>
   */
  com.ono.chain.jabci.types.RequestCheckTxOrBuilder getCheckTxOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.RequestDeliverTx deliver_tx = 19;</code>
   */
  boolean hasDeliverTx();
  /**
   * <code>.com.ono.chain.jabci.types.RequestDeliverTx deliver_tx = 19;</code>
   */
  com.ono.chain.jabci.types.RequestDeliverTx getDeliverTx();
  /**
   * <code>.com.ono.chain.jabci.types.RequestDeliverTx deliver_tx = 19;</code>
   */
  com.ono.chain.jabci.types.RequestDeliverTxOrBuilder getDeliverTxOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.RequestEndBlock end_block = 11;</code>
   */
  boolean hasEndBlock();
  /**
   * <code>.com.ono.chain.jabci.types.RequestEndBlock end_block = 11;</code>
   */
  com.ono.chain.jabci.types.RequestEndBlock getEndBlock();
  /**
   * <code>.com.ono.chain.jabci.types.RequestEndBlock end_block = 11;</code>
   */
  com.ono.chain.jabci.types.RequestEndBlockOrBuilder getEndBlockOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.RequestCommit commit = 12;</code>
   */
  boolean hasCommit();
  /**
   * <code>.com.ono.chain.jabci.types.RequestCommit commit = 12;</code>
   */
  com.ono.chain.jabci.types.RequestCommit getCommit();
  /**
   * <code>.com.ono.chain.jabci.types.RequestCommit commit = 12;</code>
   */
  com.ono.chain.jabci.types.RequestCommitOrBuilder getCommitOrBuilder();

  public com.ono.chain.jabci.types.Request.ValueCase getValueCase();
}
