// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface RequestDeliverTxOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.RequestDeliverTx)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes tx = 1;</code>
   */
  com.google.protobuf.ByteString getTx();
}
