// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface RequestCommitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.RequestCommit)
    com.google.protobuf.MessageOrBuilder {
}
