// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface ResponseFlushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.ResponseFlush)
    com.google.protobuf.MessageOrBuilder {
}
