// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface ResponseBeginBlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.ResponseBeginBlock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ono.chain.jabci.types.KVPair tags = 1;</code>
   */
  java.util.List<com.ono.chain.jabci.types.KVPair>
      getTagsList();
  /**
   * <code>repeated .com.ono.chain.jabci.types.KVPair tags = 1;</code>
   */
  com.ono.chain.jabci.types.KVPair getTags(int index);
  /**
   * <code>repeated .com.ono.chain.jabci.types.KVPair tags = 1;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .com.ono.chain.jabci.types.KVPair tags = 1;</code>
   */
  java.util.List<? extends com.ono.chain.jabci.types.KVPairOrBuilder>
      getTagsOrBuilderList();
  /**
   * <code>repeated .com.ono.chain.jabci.types.KVPair tags = 1;</code>
   */
  com.ono.chain.jabci.types.KVPairOrBuilder getTagsOrBuilder(
      int index);
}
