// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.ono.chain.jabci.types.ResponseException exception = 1;</code>
   */
  boolean hasException();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseException exception = 1;</code>
   */
  com.ono.chain.jabci.types.ResponseException getException();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseException exception = 1;</code>
   */
  com.ono.chain.jabci.types.ResponseExceptionOrBuilder getExceptionOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ResponseEcho echo = 2;</code>
   */
  boolean hasEcho();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseEcho echo = 2;</code>
   */
  com.ono.chain.jabci.types.ResponseEcho getEcho();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseEcho echo = 2;</code>
   */
  com.ono.chain.jabci.types.ResponseEchoOrBuilder getEchoOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ResponseFlush flush = 3;</code>
   */
  boolean hasFlush();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseFlush flush = 3;</code>
   */
  com.ono.chain.jabci.types.ResponseFlush getFlush();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseFlush flush = 3;</code>
   */
  com.ono.chain.jabci.types.ResponseFlushOrBuilder getFlushOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ResponseInfo info = 4;</code>
   */
  boolean hasInfo();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseInfo info = 4;</code>
   */
  com.ono.chain.jabci.types.ResponseInfo getInfo();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseInfo info = 4;</code>
   */
  com.ono.chain.jabci.types.ResponseInfoOrBuilder getInfoOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ResponseSetOption set_option = 5;</code>
   */
  boolean hasSetOption();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseSetOption set_option = 5;</code>
   */
  com.ono.chain.jabci.types.ResponseSetOption getSetOption();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseSetOption set_option = 5;</code>
   */
  com.ono.chain.jabci.types.ResponseSetOptionOrBuilder getSetOptionOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ResponseInitChain init_chain = 6;</code>
   */
  boolean hasInitChain();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseInitChain init_chain = 6;</code>
   */
  com.ono.chain.jabci.types.ResponseInitChain getInitChain();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseInitChain init_chain = 6;</code>
   */
  com.ono.chain.jabci.types.ResponseInitChainOrBuilder getInitChainOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ResponseQuery query = 7;</code>
   */
  boolean hasQuery();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseQuery query = 7;</code>
   */
  com.ono.chain.jabci.types.ResponseQuery getQuery();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseQuery query = 7;</code>
   */
  com.ono.chain.jabci.types.ResponseQueryOrBuilder getQueryOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ResponseBeginBlock begin_block = 8;</code>
   */
  boolean hasBeginBlock();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseBeginBlock begin_block = 8;</code>
   */
  com.ono.chain.jabci.types.ResponseBeginBlock getBeginBlock();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseBeginBlock begin_block = 8;</code>
   */
  com.ono.chain.jabci.types.ResponseBeginBlockOrBuilder getBeginBlockOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ResponseCheckTx check_tx = 9;</code>
   */
  boolean hasCheckTx();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseCheckTx check_tx = 9;</code>
   */
  com.ono.chain.jabci.types.ResponseCheckTx getCheckTx();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseCheckTx check_tx = 9;</code>
   */
  com.ono.chain.jabci.types.ResponseCheckTxOrBuilder getCheckTxOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ResponseDeliverTx deliver_tx = 10;</code>
   */
  boolean hasDeliverTx();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseDeliverTx deliver_tx = 10;</code>
   */
  com.ono.chain.jabci.types.ResponseDeliverTx getDeliverTx();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseDeliverTx deliver_tx = 10;</code>
   */
  com.ono.chain.jabci.types.ResponseDeliverTxOrBuilder getDeliverTxOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ResponseEndBlock end_block = 11;</code>
   */
  boolean hasEndBlock();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseEndBlock end_block = 11;</code>
   */
  com.ono.chain.jabci.types.ResponseEndBlock getEndBlock();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseEndBlock end_block = 11;</code>
   */
  com.ono.chain.jabci.types.ResponseEndBlockOrBuilder getEndBlockOrBuilder();

  /**
   * <code>.com.ono.chain.jabci.types.ResponseCommit commit = 12;</code>
   */
  boolean hasCommit();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseCommit commit = 12;</code>
   */
  com.ono.chain.jabci.types.ResponseCommit getCommit();
  /**
   * <code>.com.ono.chain.jabci.types.ResponseCommit commit = 12;</code>
   */
  com.ono.chain.jabci.types.ResponseCommitOrBuilder getCommitOrBuilder();

  public com.ono.chain.jabci.types.Response.ValueCase getValueCase();
}
