// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface ResponseInitChainOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.ResponseInitChain)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.ono.chain.jabci.types.ConsensusParams consensus_params = 1;</code>
   */
  boolean hasConsensusParams();
  /**
   * <code>.com.ono.chain.jabci.types.ConsensusParams consensus_params = 1;</code>
   */
  com.ono.chain.jabci.types.ConsensusParams getConsensusParams();
  /**
   * <code>.com.ono.chain.jabci.types.ConsensusParams consensus_params = 1;</code>
   */
  com.ono.chain.jabci.types.ConsensusParamsOrBuilder getConsensusParamsOrBuilder();

  /**
   * <code>repeated .com.ono.chain.jabci.types.ValidatorUpdate validators = 2;</code>
   */
  java.util.List<com.ono.chain.jabci.types.ValidatorUpdate>
      getValidatorsList();
  /**
   * <code>repeated .com.ono.chain.jabci.types.ValidatorUpdate validators = 2;</code>
   */
  com.ono.chain.jabci.types.ValidatorUpdate getValidators(int index);
  /**
   * <code>repeated .com.ono.chain.jabci.types.ValidatorUpdate validators = 2;</code>
   */
  int getValidatorsCount();
  /**
   * <code>repeated .com.ono.chain.jabci.types.ValidatorUpdate validators = 2;</code>
   */
  java.util.List<? extends com.ono.chain.jabci.types.ValidatorUpdateOrBuilder>
      getValidatorsOrBuilderList();
  /**
   * <code>repeated .com.ono.chain.jabci.types.ValidatorUpdate validators = 2;</code>
   */
  com.ono.chain.jabci.types.ValidatorUpdateOrBuilder getValidatorsOrBuilder(
      int index);
}
