// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface ResponseEndBlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.ResponseEndBlock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ono.chain.jabci.types.ValidatorUpdate validator_updates = 1;</code>
   */
  java.util.List<com.ono.chain.jabci.types.ValidatorUpdate> 
      getValidatorUpdatesList();
  /**
   * <code>repeated .com.ono.chain.jabci.types.ValidatorUpdate validator_updates = 1;</code>
   */
  com.ono.chain.jabci.types.ValidatorUpdate getValidatorUpdates(int index);
  /**
   * <code>repeated .com.ono.chain.jabci.types.ValidatorUpdate validator_updates = 1;</code>
   */
  int getValidatorUpdatesCount();
  /**
   * <code>repeated .com.ono.chain.jabci.types.ValidatorUpdate validator_updates = 1;</code>
   */
  java.util.List<? extends com.ono.chain.jabci.types.ValidatorUpdateOrBuilder> 
      getValidatorUpdatesOrBuilderList();
  /**
   * <code>repeated .com.ono.chain.jabci.types.ValidatorUpdate validator_updates = 1;</code>
   */
  com.ono.chain.jabci.types.ValidatorUpdateOrBuilder getValidatorUpdatesOrBuilder(
      int index);

  /**
   * <code>.com.ono.chain.jabci.types.ConsensusParams consensus_param_updates = 2;</code>
   */
  boolean hasConsensusParamUpdates();
  /**
   * <code>.com.ono.chain.jabci.types.ConsensusParams consensus_param_updates = 2;</code>
   */
  com.ono.chain.jabci.types.ConsensusParams getConsensusParamUpdates();
  /**
   * <code>.com.ono.chain.jabci.types.ConsensusParams consensus_param_updates = 2;</code>
   */
  com.ono.chain.jabci.types.ConsensusParamsOrBuilder getConsensusParamUpdatesOrBuilder();

  /**
   * <code>repeated .com.ono.chain.jabci.types.KVPair tags = 3;</code>
   */
  java.util.List<com.ono.chain.jabci.types.KVPair> 
      getTagsList();
  /**
   * <code>repeated .com.ono.chain.jabci.types.KVPair tags = 3;</code>
   */
  com.ono.chain.jabci.types.KVPair getTags(int index);
  /**
   * <code>repeated .com.ono.chain.jabci.types.KVPair tags = 3;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .com.ono.chain.jabci.types.KVPair tags = 3;</code>
   */
  java.util.List<? extends com.ono.chain.jabci.types.KVPairOrBuilder> 
      getTagsOrBuilderList();
  /**
   * <code>repeated .com.ono.chain.jabci.types.KVPair tags = 3;</code>
   */
  com.ono.chain.jabci.types.KVPairOrBuilder getTagsOrBuilder(
      int index);
}
