// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public final class Types {
  private Types() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_KVPair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_KVPair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_KI64Pair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_KI64Pair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ProofOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ProofOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_Proof_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_Proof_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_RequestEcho_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_RequestEcho_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_RequestFlush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_RequestFlush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_RequestInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_RequestInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_RequestSetOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_RequestSetOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_RequestInitChain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_RequestInitChain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_RequestQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_RequestQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_RequestBeginBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_RequestBeginBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_RequestCheckTx_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_RequestCheckTx_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_RequestDeliverTx_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_RequestDeliverTx_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_RequestEndBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_RequestEndBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_RequestCommit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_RequestCommit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseException_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseException_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseEcho_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseEcho_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseFlush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseFlush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseSetOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseSetOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseInitChain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseInitChain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseBeginBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseBeginBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseCheckTx_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseCheckTx_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseDeliverTx_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseDeliverTx_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseEndBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseEndBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ResponseCommit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ResponseCommit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ConsensusParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ConsensusParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_BlockSizeParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_BlockSizeParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_EvidenceParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_EvidenceParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ValidatorParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ValidatorParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_LastCommitInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_LastCommitInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_Version_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_Version_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_BlockID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_BlockID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_PartSetHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_PartSetHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_Validator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_Validator_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_ValidatorUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_ValidatorUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_VoteInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_VoteInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_PubKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_PubKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ono_chain_jabci_types_Evidence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ono_chain_jabci_types_Evidence_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013types.proto\022\031com.ono.chain.jabci.types" +
      "\032\037google/protobuf/timestamp.proto\"$\n\006KVP" +
      "air\022\013\n\003key\030\001 \001(\014\022\r\n\005value\030\002 \001(\014\"&\n\010KI64P" +
      "air\022\013\n\003key\030\001 \001(\014\022\r\n\005value\030\002 \001(\003\"2\n\007Proof" +
      "Op\022\014\n\004type\030\001 \001(\t\022\013\n\003key\030\002 \001(\014\022\014\n\004data\030\003 " +
      "\001(\014\"8\n\005Proof\022/\n\003ops\030\001 \003(\0132\".com.ono.chai" +
      "n.jabci.types.ProofOp\"\300\005\n\007Request\0226\n\004ech" +
      "o\030\002 \001(\0132&.com.ono.chain.jabci.types.Requ" +
      "estEchoH\000\0228\n\005flush\030\003 \001(\0132\'.com.ono.chain" +
      ".jabci.types.RequestFlushH\000\0226\n\004info\030\004 \001(" +
      "\0132&.com.ono.chain.jabci.types.RequestInf" +
      "oH\000\022A\n\nset_option\030\005 \001(\0132+.com.ono.chain." +
      "jabci.types.RequestSetOptionH\000\022A\n\ninit_c" +
      "hain\030\006 \001(\0132+.com.ono.chain.jabci.types.R" +
      "equestInitChainH\000\0228\n\005query\030\007 \001(\0132\'.com.o" +
      "no.chain.jabci.types.RequestQueryH\000\022C\n\013b" +
      "egin_block\030\010 \001(\0132,.com.ono.chain.jabci.t" +
      "ypes.RequestBeginBlockH\000\022=\n\010check_tx\030\t \001" +
      "(\0132).com.ono.chain.jabci.types.RequestCh" +
      "eckTxH\000\022A\n\ndeliver_tx\030\023 \001(\0132+.com.ono.ch" +
      "ain.jabci.types.RequestDeliverTxH\000\022?\n\ten" +
      "d_block\030\013 \001(\0132*.com.ono.chain.jabci.type" +
      "s.RequestEndBlockH\000\022:\n\006commit\030\014 \001(\0132(.co" +
      "m.ono.chain.jabci.types.RequestCommitH\000B" +
      "\007\n\005value\"\036\n\013RequestEcho\022\017\n\007message\030\001 \001(\t" +
      "\"\016\n\014RequestFlush\"J\n\013RequestInfo\022\017\n\007versi" +
      "on\030\001 \001(\t\022\025\n\rblock_version\030\002 \001(\004\022\023\n\013p2p_v" +
      "ersion\030\003 \001(\004\".\n\020RequestSetOption\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\355\001\n\020RequestInitChai" +
      "n\022(\n\004time\030\001 \001(\0132\032.google.protobuf.Timest" +
      "amp\022\020\n\010chain_id\030\002 \001(\t\022D\n\020consensus_param" +
      "s\030\003 \001(\0132*.com.ono.chain.jabci.types.Cons" +
      "ensusParams\022>\n\nvalidators\030\004 \003(\0132*.com.on" +
      "o.chain.jabci.types.ValidatorUpdate\022\027\n\017a" +
      "pp_state_bytes\030\005 \001(\014\"I\n\014RequestQuery\022\014\n\004" +
      "data\030\001 \001(\014\022\014\n\004path\030\002 \001(\t\022\016\n\006height\030\003 \001(\003" +
      "\022\r\n\005prove\030\004 \001(\010\"\334\001\n\021RequestBeginBlock\022\014\n" +
      "\004hash\030\001 \001(\014\0221\n\006header\030\002 \001(\0132!.com.ono.ch" +
      "ain.jabci.types.Header\022C\n\020last_commit_in" +
      "fo\030\003 \001(\0132).com.ono.chain.jabci.types.Las" +
      "tCommitInfo\022A\n\024byzantine_validators\030\004 \003(" +
      "\0132#.com.ono.chain.jabci.types.Evidence\"\034" +
      "\n\016RequestCheckTx\022\n\n\002tx\030\001 \001(\014\"\036\n\020RequestD" +
      "eliverTx\022\n\n\002tx\030\001 \001(\014\"!\n\017RequestEndBlock\022" +
      "\016\n\006height\030\001 \001(\003\"\017\n\rRequestCommit\"\217\006\n\010Res" +
      "ponse\022A\n\texception\030\001 \001(\0132,.com.ono.chain" +
      ".jabci.types.ResponseExceptionH\000\0227\n\004echo" +
      "\030\002 \001(\0132\'.com.ono.chain.jabci.types.Respo" +
      "nseEchoH\000\0229\n\005flush\030\003 \001(\0132(.com.ono.chain" +
      ".jabci.types.ResponseFlushH\000\0227\n\004info\030\004 \001" +
      "(\0132\'.com.ono.chain.jabci.types.ResponseI" +
      "nfoH\000\022B\n\nset_option\030\005 \001(\0132,.com.ono.chai" +
      "n.jabci.types.ResponseSetOptionH\000\022B\n\nini" +
      "t_chain\030\006 \001(\0132,.com.ono.chain.jabci.type" +
      "s.ResponseInitChainH\000\0229\n\005query\030\007 \001(\0132(.c" +
      "om.ono.chain.jabci.types.ResponseQueryH\000" +
      "\022D\n\013begin_block\030\010 \001(\0132-.com.ono.chain.ja" +
      "bci.types.ResponseBeginBlockH\000\022>\n\010check_" +
      "tx\030\t \001(\0132*.com.ono.chain.jabci.types.Res" +
      "ponseCheckTxH\000\022B\n\ndeliver_tx\030\n \001(\0132,.com" +
      ".ono.chain.jabci.types.ResponseDeliverTx" +
      "H\000\022@\n\tend_block\030\013 \001(\0132+.com.ono.chain.ja" +
      "bci.types.ResponseEndBlockH\000\022;\n\006commit\030\014" +
      " \001(\0132).com.ono.chain.jabci.types.Respons" +
      "eCommitH\000B\007\n\005value\"\"\n\021ResponseException\022" +
      "\r\n\005error\030\001 \001(\t\"\037\n\014ResponseEcho\022\017\n\007messag" +
      "e\030\001 \001(\t\"\017\n\rResponseFlush\"z\n\014ResponseInfo" +
      "\022\014\n\004data\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022\023\n\013app_v" +
      "ersion\030\003 \001(\004\022\031\n\021last_block_height\030\004 \001(\003\022" +
      "\033\n\023last_block_app_hash\030\005 \001(\014\"<\n\021Response" +
      "SetOption\022\014\n\004code\030\001 \001(\r\022\013\n\003log\030\003 \001(\t\022\014\n\004" +
      "info\030\004 \001(\t\"\231\001\n\021ResponseInitChain\022D\n\020cons" +
      "ensus_params\030\001 \001(\0132*.com.ono.chain.jabci" +
      ".types.ConsensusParams\022>\n\nvalidators\030\002 \003" +
      "(\0132*.com.ono.chain.jabci.types.Validator" +
      "Update\"\267\001\n\rResponseQuery\022\014\n\004code\030\001 \001(\r\022\013" +
      "\n\003log\030\003 \001(\t\022\014\n\004info\030\004 \001(\t\022\r\n\005index\030\005 \001(\003" +
      "\022\013\n\003key\030\006 \001(\014\022\r\n\005value\030\007 \001(\014\022/\n\005proof\030\010 " +
      "\001(\0132 .com.ono.chain.jabci.types.Proof\022\016\n" +
      "\006height\030\t \001(\003\022\021\n\tcodespace\030\n \001(\t\"E\n\022Resp" +
      "onseBeginBlock\022/\n\004tags\030\001 \003(\0132!.com.ono.c" +
      "hain.jabci.types.KVPair\"\262\001\n\017ResponseChec" +
      "kTx\022\014\n\004code\030\001 \001(\r\022\014\n\004data\030\002 \001(\014\022\013\n\003log\030\003" +
      " \001(\t\022\014\n\004info\030\004 \001(\t\022\022\n\ngas_wanted\030\005 \001(\003\022\020" +
      "\n\010gas_used\030\006 \001(\003\022/\n\004tags\030\007 \003(\0132!.com.ono" +
      ".chain.jabci.types.KVPair\022\021\n\tcodespace\030\010" +
      " \001(\t\"\264\001\n\021ResponseDeliverTx\022\014\n\004code\030\001 \001(\r" +
      "\022\014\n\004data\030\002 \001(\014\022\013\n\003log\030\003 \001(\t\022\014\n\004info\030\004 \001(" +
      "\t\022\022\n\ngas_wanted\030\005 \001(\003\022\020\n\010gas_used\030\006 \001(\003\022" +
      "/\n\004tags\030\007 \003(\0132!.com.ono.chain.jabci.type" +
      "s.KVPair\022\021\n\tcodespace\030\010 \001(\t\"\327\001\n\020Response" +
      "EndBlock\022E\n\021validator_updates\030\001 \003(\0132*.co" +
      "m.ono.chain.jabci.types.ValidatorUpdate\022" +
      "K\n\027consensus_param_updates\030\002 \001(\0132*.com.o" +
      "no.chain.jabci.types.ConsensusParams\022/\n\004" +
      "tags\030\003 \003(\0132!.com.ono.chain.jabci.types.K" +
      "VPair\"\036\n\016ResponseCommit\022\014\n\004data\030\002 \001(\014\"\315\001" +
      "\n\017ConsensusParams\022>\n\nblock_size\030\001 \001(\0132*." +
      "com.ono.chain.jabci.types.BlockSizeParam" +
      "s\022;\n\010evidence\030\002 \001(\0132).com.ono.chain.jabc" +
      "i.types.EvidenceParams\022=\n\tvalidator\030\003 \001(" +
      "\0132*.com.ono.chain.jabci.types.ValidatorP" +
      "arams\"5\n\017BlockSizeParams\022\021\n\tmax_bytes\030\001 " +
      "\001(\003\022\017\n\007max_gas\030\002 \001(\003\"!\n\016EvidenceParams\022\017" +
      "\n\007max_age\030\001 \001(\003\"(\n\017ValidatorParams\022\025\n\rpu" +
      "b_key_types\030\001 \003(\t\"S\n\016LastCommitInfo\022\r\n\005r" +
      "ound\030\001 \001(\005\0222\n\005votes\030\002 \003(\0132#.com.ono.chai" +
      "n.jabci.types.VoteInfo\"\302\003\n\006Header\0223\n\007ver" +
      "sion\030\001 \001(\0132\".com.ono.chain.jabci.types.V" +
      "ersion\022\020\n\010chain_id\030\002 \001(\t\022\016\n\006height\030\003 \001(\003" +
      "\022(\n\004time\030\004 \001(\0132\032.google.protobuf.Timesta" +
      "mp\022\017\n\007num_txs\030\005 \001(\003\022\021\n\ttotal_txs\030\006 \001(\003\0229" +
      "\n\rlast_block_id\030\007 \001(\0132\".com.ono.chain.ja" +
      "bci.types.BlockID\022\030\n\020last_commit_hash\030\010 " +
      "\001(\014\022\021\n\tdata_hash\030\t \001(\014\022\027\n\017validators_has" +
      "h\030\n \001(\014\022\034\n\024next_validators_hash\030\013 \001(\014\022\026\n" +
      "\016consensus_hash\030\014 \001(\014\022\020\n\010app_hash\030\r \001(\014\022" +
      "\031\n\021last_results_hash\030\016 \001(\014\022\025\n\revidence_h" +
      "ash\030\017 \001(\014\022\030\n\020proposer_address\030\020 \001(\014\"%\n\007V" +
      "ersion\022\r\n\005Block\030\001 \001(\004\022\013\n\003App\030\002 \001(\004\"W\n\007Bl" +
      "ockID\022\014\n\004hash\030\001 \001(\014\022>\n\014parts_header\030\002 \001(" +
      "\0132(.com.ono.chain.jabci.types.PartSetHea" +
      "der\",\n\rPartSetHeader\022\r\n\005total\030\001 \001(\005\022\014\n\004h" +
      "ash\030\002 \001(\014\"+\n\tValidator\022\017\n\007address\030\001 \001(\014\022" +
      "\r\n\005power\030\003 \001(\003\"T\n\017ValidatorUpdate\0222\n\007pub" +
      "_key\030\001 \001(\0132!.com.ono.chain.jabci.types.P" +
      "ubKey\022\r\n\005power\030\002 \001(\003\"^\n\010VoteInfo\0227\n\tvali" +
      "dator\030\001 \001(\0132$.com.ono.chain.jabci.types." +
      "Validator\022\031\n\021signed_last_block\030\002 \001(\010\"$\n\006" +
      "PubKey\022\014\n\004type\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\"\247\001\n\010E" +
      "vidence\022\014\n\004type\030\001 \001(\t\0227\n\tvalidator\030\002 \001(\013" +
      "2$.com.ono.chain.jabci.types.Validator\022\016" +
      "\n\006height\030\003 \001(\003\022(\n\004time\030\004 \001(\0132\032.google.pr" +
      "otobuf.Timestamp\022\032\n\022total_voting_power\030\005" +
      " \001(\0032\304\010\n\017ABCIApplication\022W\n\004Echo\022&.com.o" +
      "no.chain.jabci.types.RequestEcho\032\'.com.o" +
      "no.chain.jabci.types.ResponseEcho\022Z\n\005Flu" +
      "sh\022\'.com.ono.chain.jabci.types.RequestFl" +
      "ush\032(.com.ono.chain.jabci.types.Response" +
      "Flush\022W\n\004Info\022&.com.ono.chain.jabci.type" +
      "s.RequestInfo\032\'.com.ono.chain.jabci.type" +
      "s.ResponseInfo\022f\n\tSetOption\022+.com.ono.ch" +
      "ain.jabci.types.RequestSetOption\032,.com.o" +
      "no.chain.jabci.types.ResponseSetOption\022f" +
      "\n\tDeliverTx\022+.com.ono.chain.jabci.types." +
      "RequestDeliverTx\032,.com.ono.chain.jabci.t" +
      "ypes.ResponseDeliverTx\022`\n\007CheckTx\022).com." +
      "ono.chain.jabci.types.RequestCheckTx\032*.c" +
      "om.ono.chain.jabci.types.ResponseCheckTx" +
      "\022Z\n\005Query\022\'.com.ono.chain.jabci.types.Re" +
      "questQuery\032(.com.ono.chain.jabci.types.R" +
      "esponseQuery\022]\n\006Commit\022(.com.ono.chain.j" +
      "abci.types.RequestCommit\032).com.ono.chain" +
      ".jabci.types.ResponseCommit\022f\n\tInitChain" +
      "\022+.com.ono.chain.jabci.types.RequestInit" +
      "Chain\032,.com.ono.chain.jabci.types.Respon" +
      "seInitChain\022i\n\nBeginBlock\022,.com.ono.chai" +
      "n.jabci.types.RequestBeginBlock\032-.com.on" +
      "o.chain.jabci.types.ResponseBeginBlock\022c" +
      "\n\010EndBlock\022*.com.ono.chain.jabci.types.R" +
      "equestEndBlock\032+.com.ono.chain.jabci.typ" +
      "es.ResponseEndBlockB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_ono_chain_jabci_types_KVPair_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ono_chain_jabci_types_KVPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_KVPair_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_ono_chain_jabci_types_KI64Pair_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ono_chain_jabci_types_KI64Pair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_KI64Pair_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_ono_chain_jabci_types_ProofOp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ono_chain_jabci_types_ProofOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ProofOp_descriptor,
        new java.lang.String[] { "Type", "Key", "Data", });
    internal_static_com_ono_chain_jabci_types_Proof_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ono_chain_jabci_types_Proof_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_Proof_descriptor,
        new java.lang.String[] { "Ops", });
    internal_static_com_ono_chain_jabci_types_Request_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_ono_chain_jabci_types_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_Request_descriptor,
        new java.lang.String[] { "Echo", "Flush", "Info", "SetOption", "InitChain", "Query", "BeginBlock", "CheckTx", "DeliverTx", "EndBlock", "Commit", "Value", });
    internal_static_com_ono_chain_jabci_types_RequestEcho_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_ono_chain_jabci_types_RequestEcho_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_RequestEcho_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_ono_chain_jabci_types_RequestFlush_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_ono_chain_jabci_types_RequestFlush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_RequestFlush_descriptor,
        new java.lang.String[] { });
    internal_static_com_ono_chain_jabci_types_RequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_ono_chain_jabci_types_RequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_RequestInfo_descriptor,
        new java.lang.String[] { "Version", "BlockVersion", "P2PVersion", });
    internal_static_com_ono_chain_jabci_types_RequestSetOption_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_ono_chain_jabci_types_RequestSetOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_RequestSetOption_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_ono_chain_jabci_types_RequestInitChain_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_ono_chain_jabci_types_RequestInitChain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_RequestInitChain_descriptor,
        new java.lang.String[] { "Time", "ChainId", "ConsensusParams", "Validators", "AppStateBytes", });
    internal_static_com_ono_chain_jabci_types_RequestQuery_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_ono_chain_jabci_types_RequestQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_RequestQuery_descriptor,
        new java.lang.String[] { "Data", "Path", "Height", "Prove", });
    internal_static_com_ono_chain_jabci_types_RequestBeginBlock_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_ono_chain_jabci_types_RequestBeginBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_RequestBeginBlock_descriptor,
        new java.lang.String[] { "Hash", "Header", "LastCommitInfo", "ByzantineValidators", });
    internal_static_com_ono_chain_jabci_types_RequestCheckTx_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_ono_chain_jabci_types_RequestCheckTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_RequestCheckTx_descriptor,
        new java.lang.String[] { "Tx", });
    internal_static_com_ono_chain_jabci_types_RequestDeliverTx_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_ono_chain_jabci_types_RequestDeliverTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_RequestDeliverTx_descriptor,
        new java.lang.String[] { "Tx", });
    internal_static_com_ono_chain_jabci_types_RequestEndBlock_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_ono_chain_jabci_types_RequestEndBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_RequestEndBlock_descriptor,
        new java.lang.String[] { "Height", });
    internal_static_com_ono_chain_jabci_types_RequestCommit_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_ono_chain_jabci_types_RequestCommit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_RequestCommit_descriptor,
        new java.lang.String[] { });
    internal_static_com_ono_chain_jabci_types_Response_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_ono_chain_jabci_types_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_Response_descriptor,
        new java.lang.String[] { "Exception", "Echo", "Flush", "Info", "SetOption", "InitChain", "Query", "BeginBlock", "CheckTx", "DeliverTx", "EndBlock", "Commit", "Value", });
    internal_static_com_ono_chain_jabci_types_ResponseException_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_ono_chain_jabci_types_ResponseException_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseException_descriptor,
        new java.lang.String[] { "Error", });
    internal_static_com_ono_chain_jabci_types_ResponseEcho_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_ono_chain_jabci_types_ResponseEcho_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseEcho_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_ono_chain_jabci_types_ResponseFlush_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_ono_chain_jabci_types_ResponseFlush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseFlush_descriptor,
        new java.lang.String[] { });
    internal_static_com_ono_chain_jabci_types_ResponseInfo_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_ono_chain_jabci_types_ResponseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseInfo_descriptor,
        new java.lang.String[] { "Data", "Version", "AppVersion", "LastBlockHeight", "LastBlockAppHash", });
    internal_static_com_ono_chain_jabci_types_ResponseSetOption_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_ono_chain_jabci_types_ResponseSetOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseSetOption_descriptor,
        new java.lang.String[] { "Code", "Log", "Info", });
    internal_static_com_ono_chain_jabci_types_ResponseInitChain_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_ono_chain_jabci_types_ResponseInitChain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseInitChain_descriptor,
        new java.lang.String[] { "ConsensusParams", "Validators", });
    internal_static_com_ono_chain_jabci_types_ResponseQuery_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_ono_chain_jabci_types_ResponseQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseQuery_descriptor,
        new java.lang.String[] { "Code", "Log", "Info", "Index", "Key", "Value", "Proof", "Height", "Codespace", });
    internal_static_com_ono_chain_jabci_types_ResponseBeginBlock_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_ono_chain_jabci_types_ResponseBeginBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseBeginBlock_descriptor,
        new java.lang.String[] { "Tags", });
    internal_static_com_ono_chain_jabci_types_ResponseCheckTx_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_ono_chain_jabci_types_ResponseCheckTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseCheckTx_descriptor,
        new java.lang.String[] { "Code", "Data", "Log", "Info", "GasWanted", "GasUsed", "Tags", "Codespace", });
    internal_static_com_ono_chain_jabci_types_ResponseDeliverTx_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_com_ono_chain_jabci_types_ResponseDeliverTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseDeliverTx_descriptor,
        new java.lang.String[] { "Code", "Data", "Log", "Info", "GasWanted", "GasUsed", "Tags", "Codespace", });
    internal_static_com_ono_chain_jabci_types_ResponseEndBlock_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_com_ono_chain_jabci_types_ResponseEndBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseEndBlock_descriptor,
        new java.lang.String[] { "ValidatorUpdates", "ConsensusParamUpdates", "Tags", });
    internal_static_com_ono_chain_jabci_types_ResponseCommit_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_com_ono_chain_jabci_types_ResponseCommit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ResponseCommit_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_com_ono_chain_jabci_types_ConsensusParams_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_com_ono_chain_jabci_types_ConsensusParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ConsensusParams_descriptor,
        new java.lang.String[] { "BlockSize", "Evidence", "Validator", });
    internal_static_com_ono_chain_jabci_types_BlockSizeParams_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_com_ono_chain_jabci_types_BlockSizeParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_BlockSizeParams_descriptor,
        new java.lang.String[] { "MaxBytes", "MaxGas", });
    internal_static_com_ono_chain_jabci_types_EvidenceParams_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_com_ono_chain_jabci_types_EvidenceParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_EvidenceParams_descriptor,
        new java.lang.String[] { "MaxAge", });
    internal_static_com_ono_chain_jabci_types_ValidatorParams_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_com_ono_chain_jabci_types_ValidatorParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ValidatorParams_descriptor,
        new java.lang.String[] { "PubKeyTypes", });
    internal_static_com_ono_chain_jabci_types_LastCommitInfo_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_com_ono_chain_jabci_types_LastCommitInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_LastCommitInfo_descriptor,
        new java.lang.String[] { "Round", "Votes", });
    internal_static_com_ono_chain_jabci_types_Header_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_com_ono_chain_jabci_types_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_Header_descriptor,
        new java.lang.String[] { "Version", "ChainId", "Height", "Time", "NumTxs", "TotalTxs", "LastBlockId", "LastCommitHash", "DataHash", "ValidatorsHash", "NextValidatorsHash", "ConsensusHash", "AppHash", "LastResultsHash", "EvidenceHash", "ProposerAddress", });
    internal_static_com_ono_chain_jabci_types_Version_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_com_ono_chain_jabci_types_Version_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_Version_descriptor,
        new java.lang.String[] { "Block", "App", });
    internal_static_com_ono_chain_jabci_types_BlockID_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_com_ono_chain_jabci_types_BlockID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_BlockID_descriptor,
        new java.lang.String[] { "Hash", "PartsHeader", });
    internal_static_com_ono_chain_jabci_types_PartSetHeader_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_com_ono_chain_jabci_types_PartSetHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_PartSetHeader_descriptor,
        new java.lang.String[] { "Total", "Hash", });
    internal_static_com_ono_chain_jabci_types_Validator_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_com_ono_chain_jabci_types_Validator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_Validator_descriptor,
        new java.lang.String[] { "Address", "Power", });
    internal_static_com_ono_chain_jabci_types_ValidatorUpdate_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_com_ono_chain_jabci_types_ValidatorUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_ValidatorUpdate_descriptor,
        new java.lang.String[] { "PubKey", "Power", });
    internal_static_com_ono_chain_jabci_types_VoteInfo_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_com_ono_chain_jabci_types_VoteInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_VoteInfo_descriptor,
        new java.lang.String[] { "Validator", "SignedLastBlock", });
    internal_static_com_ono_chain_jabci_types_PubKey_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_com_ono_chain_jabci_types_PubKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_PubKey_descriptor,
        new java.lang.String[] { "Type", "Data", });
    internal_static_com_ono_chain_jabci_types_Evidence_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_com_ono_chain_jabci_types_Evidence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ono_chain_jabci_types_Evidence_descriptor,
        new java.lang.String[] { "Type", "Validator", "Height", "Time", "TotalVotingPower", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
