// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface ValidatorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.Validator)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes address = 1;</code>
   */
  com.google.protobuf.ByteString getAddress();

  /**
   * <pre>
   *PubKey pub_key = 2 ;
   * </pre>
   *
   * <code>int64 power = 3;</code>
   */
  long getPower();
}
