// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.ono.chain.jabci.types;

public interface ValidatorUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ono.chain.jabci.types.ValidatorUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.ono.chain.jabci.types.PubKey pub_key = 1;</code>
   */
  boolean hasPubKey();
  /**
   * <code>.com.ono.chain.jabci.types.PubKey pub_key = 1;</code>
   */
  com.ono.chain.jabci.types.PubKey getPubKey();
  /**
   * <code>.com.ono.chain.jabci.types.PubKey pub_key = 1;</code>
   */
  com.ono.chain.jabci.types.PubKeyOrBuilder getPubKeyOrBuilder();

  /**
   * <code>int64 power = 2;</code>
   */
  long getPower();
}
